export const BasicData = {};

BasicData.moves = {
    "basic": {
        "actUnderPressure": {
            "title": "Act Under Pressure",
            "description": "When you do something under pressure or endure duress, roll +Cool.",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityCool"],
            "fullHit": "You do it.",
            "partialHit": "The MC can offer you success at a cost — a worse outcome, a hard bargain, or an ugly choice.",
            "miss": "",
            "options": "",
        },
        "readADireSituation": {
            "title": "Read a Dire Situation",
            "description": "When you read a Dire Situation, roll +Clever. On a hit, you can ask the MC questions. Whenever you act on one of the MC's answers, take +1 forward. On a 10+, ask 3.  On a 7-9, ask 1:",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityClever"],
            "fullHit": "Ask 3:",
            "partialHit": "Ask 1:",
            "miss": "",
            "options": "<ul><li>Where's my best escape route / way in / way past?</li><li>Who or what is the biggest threat?</li><li>Who is willing to talk?</li><li>What should I be on the lookout for?</li><li>Who stands to lose/gain the most?</li><li>Who is in control here?</li></ul>",
        },
        "controlADireSituation": {
            "title": "Control a Dire Situation",
            "description": "When you take control of a Dire Situation with direct, physical action, roll +Bold. On a 10+, choose 3. On a 7-9, choose 2:",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityBold"],
            "fullHit": "Choose 3:",
            "partialHit": "Choose 2:",
            "miss": "",
            "options": "<ul><li>You indisputably take control of the situation.</li><li>You avoid the worst of the danger. Take +1 when you Tempt Fate.</li><li>You overcome all of your opponents.</li><li>You impress, dismay, or frighten your opponents and any witnesses.</li><li>No innocent bystanders are caught in the crossfire.</li></ul>",
        },
        "run": {
            "title": "RUN!",
            "description": "When you escape from a Dire Situation, Roll +Cool and run for your life. On a 10+, choose 3. On a 7-9, choose 2. In any event, mark experience.",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityCool"],
            "fullHit": "Choose 3:",
            "partialHit": "Choose 2:",
            "miss": "",
            "options": "<ul><li>You escape without Tempting Fate.</li><li>One person (of your choice) who follows you is safe; they do not Tempt Fate.</li><li>The threat loses track of where you are.</li><li>You know where you're going.</li></ul>",
        },
        "helpingOrHindering": {
            "title": "Helping or Hindering",
            "description": "When you assist, or get in the way, of someone else's move, briefly describe how you have the means to get involved. The other person takes +1 or -2 forward, respectively. This counts as making a move in a Dire Situation.<br/>Multiple people may Help or Hinder the same person, but the bonuses are not cumulative. If you make this move after the other person rolls, spend 1-Fate.",
            "type": "now",
            "stat": [],
            "fullHit": "",
            "partialHit": "",
            "miss": "",
            "options": "",
        },
        "readAPerson": {
            "title": "Read a Person",
            "description": "When you look beneath the surface while interacting with a sentient being, roll +Clever. On a 10+, hold 3. On a 7-9, hold 1. While you're interacting with them, spend your hold to ask their player questions, 1 for 1:",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityClever"],
            "fullHit": "Hold 3. While interacting with the person you're reading, spend your hold to ask their player questions, 1 for 1.",
            "partialHit": "Hold 1. While interacting with the person you're reading, spend your hold to ask their player questions, 1 for 1.",
            "miss": "",
            "options": "<ul><li> Is your character telling the truth?</li><li> What's your character really feeling?</li><li> What does your character intend to do?</li><li> What does your character wish I'd do?</li><li> How could I get your character to ...?</li></ul>",
        },
        "convinceAPerson": {
            "title": "Convince a Person",
            "description": "When you have have leverage and attempt to convince someone ... <ul><li>...with reason, roll +Clever.</li><li>...with an appeal to the emotions, roll +Appeal.</li><li>...with intimidation, roll +Bold.</li></ul>For NPCs, on a 10+, they do what you want. On a 7-9, they do what you want, but with some strings attached.<br/>With PCs, on a 10+, take both of the following. On a 7-9, choose one of the following:<ul><li>If they do it, mark experience.</li><li>If they don't do it, they're Acting under Pressure.</li></ul>",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityClever", "COMPANIONS.AbilityAppeal", "COMPANIONS.AbilityBold"],
            "fullHit": "NPCs do what you want. For PCs, take both of the following:<ul><li>If they do it, mark experience.</li><li>If they don't do it, they're Acting under Pressure.</li></ul>",
            "partialHit": "NPCs do what you want, but with some strings attached. For PCs, choose one of the following:<ul><li>If they do it, mark experience.</li><li>If they don't do it, they're Acting under Pressure.</li></ul>",
            "miss": "",
            "options": "",
        },
        "useUnfamiliarTechnology": {
            "title": "Use Unfamiliar Technology",
            "description": "Whenever using a technology unknown to you, roll +Vortex. On a 10+, it works without problems. On a 7-9, it works once, but it breaks. Only a Whiz or an appropriate NPC can fix it. On a miss, someone gets hurt, the device is destroyed, or there are unforeseen consequences.",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityVortex"],
            "fullHit": "It works without problems.",
            "partialHit": "It works once, but it breaks. Only a Whiz or an appropriate NPC can fix it.",
            "miss": "Someone gets hurt, the device is destroyed, or there are unforeseen consequences.",
            "options": "",
        },
        "talkToHer": {
            "title": "Talk to Her",
            "description": "When you attune your mind to the sprawling, inhuman intelligence at the heart of the TARDIS, roll +Vortex. For a short period, you let her in, and she shows you things. The images are disjointed and sometimes horrifying.<br/>On a hit, the MC will tell you something new and interesting about the current situation, and might ask you a question or two; answer them. On a 10+, the MC will give you good detail. On a 7-9, the MC will give you a good impression. If you already know all there is to know, the MC will tell you that.",
            "type": "roll",
            "stat": ["COMPANIONS.AbilityVortex"],
            "fullHit": "The MC will tell you something new and interesting about the current situation, and might ask you a question or two; answer them. The MC will give you good detail. If you already know all there is to know, the MC will tell you that.",
            "partialHit": "The MC will tell you something new and interesting about the current situation, and might ask you a question or two; answer them. The MC will give you a good impression. If you already know all there is to know, the MC will tell you that.",
            "miss": "",
            "options": "",
        },
        "bondWithAPerson": {
            "title": "Bond with a Person",
            "description": "When you have down time and connect with someone, open up and tell them something you hold dear: a worry, a fear, a secret, a belief-something important.<br/>Then, roll +Bond with them. On a hit, reduce both of your Fates to 6:00, and clear all stress tags on you both. On a 10+, their history with you goes up by 1. On a miss, they take an appropriate stress tag. You cannot bond with each other until it clears.<br/>If the person you're bonding with is your romantic interest, take +1 now.",
            "type": "roll",
            "stat": ["history"],
            "fullHit": "Reduce both of your Fates to 6:00, and clear all stress tags on you both. Their history with you goes up by 1.",
            "partialHit": "Reduce both of your Fates to 6:00, and clear all stress tags on you both.",
            "miss": "They take an appropriate stress tag. You cannot bond with each other until it clears.",
            "options": "",
        },
    },
    "vortex": {
        "eyesOpenedWide": {
            "title": "Eyes Opened Wide",
            "description": "+1 Vortex (Vortex +1). You become hyper-aware of your position in spacetime. When you Read a Dire Situation, you may choose to roll +Vortex instead of +Clever. Also, your new senses allow you to detect energy and matter like the Agent's Vortex Manipulator.",
            "type": "now",
            "stat": [],
            "fullHit": "",
            "partialHit": "",
            "miss": "",
            "options": "",
        },
    }
};
