export const ConstructData = {};

ConstructData.playbook = {
  "eideticPolymath" : {
    "title" : "Eidetic Polymath",
    "description" : "Not much gets past you. And what you don’t notice you can almost always infer from known variables. Your memory is perfect, as well. +1 Clever (Clever +3)",
    "type" : "now",
    "stat" : [],
    "fullHit" : "",
    "partialHit" : "",
    "miss" : "",
    "options" : "",
   },
  "theCalculusOfDeath" : {
    "title" : "The Calculus of Death",
    "description" : "Your accelerated synthetic mind can analyze enemies and calculate all possible outcomes. When you Control a Dire Situation, use Clever instead of Bold.",
    "type" : "now",
    "stat" : [],
    "fullHit" : "",
    "partialHit" : "",
    "miss" : "",
    "options" : "",
  },
  "madeOfHarderStuff" : {
    "title" : "Made of Harder Stuff",
    "description" : "You are immune to all stress tags, and you cannot be stunned.",
    "type" : "now",
    "stat" : [],
    "fullHit" : "",
    "partialHit" : "",
    "miss" : "",
    "options" : "",
  },
  "inTheDoctorsImage" : {
    "title" : "In the Doctor's Image",
    "description" : "You were designed by the Doctor, and therefore value sentient life above all things. Take +1 forward when you use a +stun weapon.",
    "type" : "now",
    "stat" : [],
    "fullHit" : "",
    "partialHit" : "",
    "miss" : "",
    "options" : "",
  },
  "todayYouGetToLive" : {
    "title" : "Today You Get to Live",
    "description" : "Today You Get to Live: When someone you value dies, you may slightly bend time to position yourself to switch places with them. When you do this, mark an experience circle, die, and make The Death Move.",
    "type" : "now",
    "stat" : [],
    "fullHit" : "",
    "partialHit" : "",
    "miss" : "",
    "options" : "",
  },
};

ConstructData.romance = {
  "title" : "",
  "description" : "Sometimes biological beings fall for you. When you can manage a moment of intimacy, their History with you resets, and you mark experience. It’s usually a bizarre experience for them, and an enlightening one for you.",
  "type" : "now",
  "stat" : [],
  "fullHit" : "",
  "partialHit" : "",
  "miss" : "",
  "options" : "",
};